#!/usr/bin/env bash

##
### Copyright 2013, Boundary
###
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###
###     http://www.apache.org/licenses/LICENSE-2.0
###
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.
###

JAVA_BIN=`which java`
if [ -z "$ZC_PATH" ]; then
    ZC_BASEDIR=`dirname "$0"`
    ZC_BASEDIR=`cd "$ZC_BASEDIR" && pwd`
    ZC_PATH="$ZC_BASEDIR/target/zoocreeper-1.0-SNAPSHOT.jar"
fi

if [ ! -f "$ZC_PATH" ]; then
    echo "Distribution not found: $ZC_PATH" >&2
    exit 1
fi

case "$1" in
    dump)
        shift
        exec $JAVA_BIN -cp $ZC_PATH com.boundary.zoocreeper.Backup "$@"
        ;;
    load)
        shift
        exec $JAVA_BIN -cp $ZC_PATH com.boundary.zoocreeper.Restore "$@"
        ;;
    *)
        echo "Usage: $0 {dump|load}" >&2
        exit 1
esac
